"""创建 Shadow Ledger v1 完整模式

Revision ID: bd7c25fb5d21
Revises:
Create Date: 2026-08-19 19:32:30.502196
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bd7c25fb5d21"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("asset_reference_id", sa.Uuid(), nullable=True),
        sa.Column("usage", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_id", "asset_id", "usage"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_aggregate",
        "audit_events",
        ["aggregate_type", "aggregate_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','running','succeeded','failed')", name="ck_job_state"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("idx_jobs_ready", "background_jobs", ["available_at", "id"], unique=False)
    op.create_table(
        "capture_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_external_id", sa.Text(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("parser", sa.String(length=80), nullable=True),
        sa.Column("parser_version", sa.String(length=40), nullable=True),
        sa.Column("capture_state", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "capture_state IN ('received','processing','parsed','failed')", name="ck_capture_state"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_capture_external",
        "capture_sources",
        ["owner_id", "source_type", "source_external_id"],
        unique=True,
        postgresql_where="source_external_id IS NOT NULL",
    )
    op.create_table(
        "external_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("target_uri", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_id", "relation", "target_uri"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.LargeBinary(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "operation", "idempotency_key"),
    )
    op.create_table(
        "identity_suggestions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("suggestion_key", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "suggestion_key"),
    )
    op.create_table(
        "ledger_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("record_kind", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(state='draft' AND confirmed_at IS NULL AND voided_at IS NULL) OR (state='confirmed' AND confirmed_at IS NOT NULL AND voided_at IS NULL) OR (state='voided' AND confirmed_at IS NOT NULL AND voided_at IS NOT NULL)",
            name="ck_record_state_times",
        ),
        sa.CheckConstraint("record_kind IN ('money_only','consumption')", name="ck_record_kind"),
        sa.CheckConstraint("state IN ('draft','confirmed','voided')", name="ck_record_state"),
        sa.CheckConstraint("revision > 0", name="ck_record_revision"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_records_owner_state",
        "ledger_records",
        ["owner_id", "state", "updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_records_owner_time", "ledger_records", ["owner_id", "occurred_at", "id"], unique=False
    )
    op.create_table(
        "local_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("merchant_type", sa.String(length=50), nullable=True),
        sa.Column("place_ref", sa.Text(), nullable=True),
        sa.Column("canonical_merchant_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "canonical_merchant_id IS NULL OR canonical_merchant_id <> id",
            name="ck_merchant_redirect",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_merchants_owner_name", "merchants", ["owner_id", "canonical_name"], unique=False
    )
    op.create_table(
        "money_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "key"),
    )
    op.create_table(
        "oidc_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state_hash", sa.LargeBinary(), nullable=False),
        sa.Column("browser_binding_hash", sa.LargeBinary(), nullable=False),
        sa.Column("nonce_hash", sa.LargeBinary(), nullable=False),
        sa.Column("pkce_verifier_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("return_to", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_outbox_pending", "outbox_events", ["available_at", "id"], unique=False)
    op.create_table(
        "reminders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("reminder_key", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','read','handled','dismissed')", name="ck_reminder_state"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "reminder_key"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "browser_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("session_hash", sa.LargeBinary(), nullable=False),
        sa.Column("groups_snapshot", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["local_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_hash"),
    )
    op.create_table(
        "budget_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("budget_month", sa.Date(), nullable=False),
        sa.Column("monthly_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("monthly_amount > 0", name="ck_budget_amount"),
        sa.CheckConstraint("revision > 0", name="ck_budget_revision"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["money_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_budget_category_active",
        "budget_targets",
        ["owner_id", "currency", "budget_month", "category_id"],
        unique=True,
        postgresql_where="category_id IS NOT NULL AND active",
    )
    op.create_index(
        "uq_budget_total_active",
        "budget_targets",
        ["owner_id", "currency", "budget_month"],
        unique=True,
        postgresql_where="category_id IS NULL AND active",
    )
    op.create_table(
        "item_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("variant", sa.Text(), nullable=True),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("external_ids", sa.JSON(), nullable=False),
        sa.Column("canonical_item_id", sa.Uuid(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('product','dish','drink','service','subscription','ticket','digital_good','other')",
            name="ck_item_kind",
        ),
        sa.CheckConstraint(
            "canonical_item_id IS NULL OR canonical_item_id <> id", name="ck_item_redirect"
        ),
        sa.ForeignKeyConstraint(
            ["canonical_item_id"],
            ["item_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_items_owner_name", "item_identities", ["owner_id", "canonical_name"], unique=False
    )
    op.create_table(
        "ledger_record_sources",
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["ledger_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["capture_sources.id"],
        ),
        sa.PrimaryKeyConstraint("record_id", "source_id", "role"),
    )
    op.create_table(
        "merchant_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "normalized_alias"),
    )
    op.create_table(
        "money_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("related_entry_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("type IN ('expense','income','refund')", name="ck_money_type"),
        sa.CheckConstraint("amount > 0", name="ck_money_amount"),
        sa.CheckConstraint(
            "related_entry_id IS NULL OR related_entry_id <> id", name="ck_money_related"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["money_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["ledger_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_entry_id"],
            ["money_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "record_id"),
        sa.UniqueConstraint("record_id"),
    )
    op.create_table(
        "consumption_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("money_entry_id", sa.Uuid(), nullable=True),
        sa.Column("scene", sa.String(length=30), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_name_raw", sa.Text(), nullable=True),
        sa.Column("channel_key", sa.String(length=50), nullable=True),
        sa.Column("channel_name_raw", sa.Text(), nullable=True),
        sa.Column("place_ref", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("would_repeat", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scene IN ('online_purchase','offline_purchase','delivery','dine_in','drink','service','subscription','transport','entertainment','travel','other')",
            name="ck_consumption_scene",
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 5", name="ck_consumption_rating"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["money_entry_id", "record_id"],
            ["money_entries.id", "money_entries.record_id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["ledger_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("money_entry_id"),
        sa.UniqueConstraint("record_id"),
    )
    op.create_table(
        "item_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_identity_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_identity_id"],
            ["item_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_identity_id", "normalized_alias"),
    )
    op.create_table(
        "recurring_commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("item_identity_id", sa.Uuid(), nullable=True),
        sa.Column("expected_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("recurrence_rule", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("remind_before_seconds", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("last_record_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('subscription','membership','regular_service','regular_purchase','fixed_expense','regular_income')",
            name="ck_commitment_kind",
        ),
        sa.CheckConstraint("state IN ('active','paused','ended')", name="ck_commitment_state"),
        sa.CheckConstraint(
            "expected_amount IS NULL OR expected_amount > 0", name="ck_commitment_amount"
        ),
        sa.ForeignKeyConstraint(
            ["item_identity_id"],
            ["item_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_record_id"],
            ["ledger_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_recurring_due",
        "recurring_commitments",
        ["owner_id", "state", "next_due_at"],
        unique=False,
    )
    op.create_table(
        "spending_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("intent_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("item_identity_id", sa.Uuid(), nullable=True),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("place_ref", sa.Text(), nullable=True),
        sa.Column("expected_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("desired_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desired_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("completed_record_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intent_type IN ('buy','eat','drink','visit','subscribe','renew','cancel','replace','other')",
            name="ck_intent_type",
        ),
        sa.CheckConstraint("priority IN ('low','normal','high')", name="ck_intent_priority"),
        sa.CheckConstraint(
            "state IN ('inbox','considering','planned','due','completed','skipped','cancelled')",
            name="ck_intent_state",
        ),
        sa.CheckConstraint(
            "desired_end IS NULL OR desired_start IS NULL OR desired_end >= desired_start",
            name="ck_intent_dates",
        ),
        sa.ForeignKeyConstraint(
            ["completed_record_id"],
            ["ledger_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_identity_id"],
            ["item_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_intents_owner_state",
        "spending_intents",
        ["owner_id", "state", "desired_start"],
        unique=False,
    )
    op.create_table(
        "consumption_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("item_identity_id", sa.Uuid(), nullable=True),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("content_category", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity IS NULL OR quantity > 0", name="ck_line_quantity"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["consumption_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_identity_id"],
            ["item_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lines_event", "consumption_lines", ["event_id", "sort_order", "id"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION ledger_validate_record_transition() RETURNS trigger AS $$
            BEGIN
              IF (OLD.state = 'draft' AND NEW.state NOT IN ('draft','confirmed'))
                 OR (OLD.state = 'confirmed' AND NEW.state NOT IN ('confirmed','voided'))
                 OR (OLD.state = 'voided' AND NEW.state <> 'voided') THEN
                RAISE EXCEPTION 'invalid ledger record state transition';
              END IF;
              IF NEW.revision <> OLD.revision + 1 THEN
                RAISE EXCEPTION 'ledger record revision must increment by one';
              END IF;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_ledger_record_transition
            BEFORE UPDATE ON ledger_records
            FOR EACH ROW EXECUTE FUNCTION ledger_validate_record_transition();

            CREATE FUNCTION ledger_validate_record_aggregate() RETURNS trigger AS $$
            DECLARE rid uuid; kind text; event_count integer;
            BEGIN
              IF TG_TABLE_NAME = 'ledger_records' THEN
                rid := COALESCE(NEW.id, OLD.id);
              ELSE
                rid := COALESCE(NEW.record_id, OLD.record_id);
              END IF;
              SELECT record_kind INTO kind FROM ledger_records WHERE id = rid;
              IF kind IS NULL THEN RETURN NULL; END IF;
              SELECT count(*) INTO event_count FROM consumption_events WHERE record_id = rid;
              IF (kind = 'money_only' AND event_count <> 0)
                 OR (kind = 'consumption' AND event_count <> 1) THEN
                RAISE EXCEPTION 'ledger record aggregate invariant failed';
              END IF;
              RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;

            CREATE CONSTRAINT TRIGGER trg_record_aggregate_record
            AFTER INSERT OR UPDATE ON ledger_records DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION ledger_validate_record_aggregate();
            CREATE CONSTRAINT TRIGGER trg_record_aggregate_event
            AFTER INSERT OR UPDATE OR DELETE ON consumption_events DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION ledger_validate_record_aggregate();

            CREATE FUNCTION ledger_validate_money_owner() RETURNS trigger AS $$
            DECLARE record_owner text; related_owner text; category_owner text;
            BEGIN
              SELECT owner_id INTO record_owner FROM ledger_records WHERE id = NEW.record_id;
              IF NEW.category_id IS NOT NULL THEN
                SELECT owner_id INTO category_owner FROM money_categories WHERE id = NEW.category_id;
                IF category_owner IS DISTINCT FROM record_owner THEN
                  RAISE EXCEPTION 'money category owner mismatch';
                END IF;
              END IF;
              IF NEW.related_entry_id IS NOT NULL THEN
                SELECT r.owner_id INTO related_owner FROM money_entries m
                  JOIN ledger_records r ON r.id = m.record_id WHERE m.id = NEW.related_entry_id;
                IF related_owner IS DISTINCT FROM record_owner THEN
                  RAISE EXCEPTION 'related entry owner mismatch';
                END IF;
              END IF;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER trg_money_owner BEFORE INSERT OR UPDATE ON money_entries
            FOR EACH ROW EXECUTE FUNCTION ledger_validate_money_owner();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            DROP TRIGGER IF EXISTS trg_money_owner ON money_entries;
            DROP FUNCTION IF EXISTS ledger_validate_money_owner();
            DROP TRIGGER IF EXISTS trg_record_aggregate_event ON consumption_events;
            DROP TRIGGER IF EXISTS trg_record_aggregate_record ON ledger_records;
            DROP FUNCTION IF EXISTS ledger_validate_record_aggregate();
            DROP TRIGGER IF EXISTS trg_ledger_record_transition ON ledger_records;
            DROP FUNCTION IF EXISTS ledger_validate_record_transition();
            """
        )
    op.drop_index("idx_lines_event", table_name="consumption_lines")
    op.drop_table("consumption_lines")
    op.drop_index("idx_intents_owner_state", table_name="spending_intents")
    op.drop_table("spending_intents")
    op.drop_index("idx_recurring_due", table_name="recurring_commitments")
    op.drop_table("recurring_commitments")
    op.drop_table("item_aliases")
    op.drop_table("consumption_events")
    op.drop_table("money_entries")
    op.drop_table("merchant_aliases")
    op.drop_table("ledger_record_sources")
    op.drop_index("idx_items_owner_name", table_name="item_identities")
    op.drop_table("item_identities")
    op.drop_index(
        "uq_budget_total_active",
        table_name="budget_targets",
        postgresql_where="category_id IS NULL AND active",
    )
    op.drop_index(
        "uq_budget_category_active",
        table_name="budget_targets",
        postgresql_where="category_id IS NOT NULL AND active",
    )
    op.drop_table("budget_targets")
    op.drop_table("browser_sessions")
    op.drop_table("user_preferences")
    op.drop_table("reminders")
    op.drop_index("idx_outbox_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("oidc_transactions")
    op.drop_table("money_categories")
    op.drop_index("idx_merchants_owner_name", table_name="merchants")
    op.drop_table("merchants")
    op.drop_table("local_identities")
    op.drop_index("idx_records_owner_time", table_name="ledger_records")
    op.drop_index("idx_records_owner_state", table_name="ledger_records")
    op.drop_table("ledger_records")
    op.drop_table("identity_suggestions")
    op.drop_table("idempotency_records")
    op.drop_table("external_references")
    op.drop_index(
        "uq_capture_external",
        table_name="capture_sources",
        postgresql_where="source_external_id IS NOT NULL",
    )
    op.drop_table("capture_sources")
    op.drop_index("idx_jobs_ready", table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index("idx_audit_aggregate", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("asset_bindings")
    # ### end Alembic commands ###
