-- Shadow Ledger v1 logical PostgreSQL schema.
-- This is a design contract, not an executable migration history.
-- IDs are generated by the application (UUIDv7 preferred).

CREATE TABLE ledger_records (
    id              UUID PRIMARY KEY,
    owner_id        TEXT NOT NULL,
    record_kind     TEXT NOT NULL CHECK (record_kind IN ('money_only', 'consumption')),
    state           TEXT NOT NULL CHECK (state IN ('draft', 'confirmed', 'voided')),
    occurred_at     TIMESTAMPTZ NOT NULL,
    timezone        TEXT NOT NULL DEFAULT 'Asia/Shanghai',
    note            TEXT NOT NULL DEFAULT '',
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    confirmed_at    TIMESTAMPTZ,
    voided_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((state = 'draft' AND confirmed_at IS NULL AND voided_at IS NULL)
        OR (state = 'confirmed' AND confirmed_at IS NOT NULL AND voided_at IS NULL)
        OR (state = 'voided' AND confirmed_at IS NOT NULL AND voided_at IS NOT NULL))
);

CREATE INDEX idx_ledger_records_owner_time
    ON ledger_records (owner_id, occurred_at DESC, id);
CREATE INDEX idx_ledger_records_owner_state
    ON ledger_records (owner_id, state, updated_at DESC);

CREATE TABLE money_categories (
    id              UUID PRIMARY KEY,
    owner_id        TEXT NOT NULL,
    key             TEXT NOT NULL,
    name            TEXT NOT NULL,
    color           TEXT,
    icon            TEXT,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, key)
);

CREATE TABLE capture_sources (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_external_id  TEXT,
    asset_id            UUID,
    raw_text            TEXT,
    raw_payload         JSONB,
    parser              TEXT,
    parser_version      TEXT,
    capture_state       TEXT NOT NULL CHECK (
        capture_state IN ('received', 'processing', 'parsed', 'failed')
    ),
    error_code          TEXT,
    captured_at         TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_capture_sources_external
    ON capture_sources (owner_id, source_type, source_external_id)
    WHERE source_external_id IS NOT NULL;

CREATE TABLE money_entries (
    id                  UUID PRIMARY KEY,
    record_id           UUID NOT NULL UNIQUE REFERENCES ledger_records(id),
    type                TEXT NOT NULL CHECK (type IN ('expense', 'income', 'refund')),
    amount              NUMERIC(18,4) NOT NULL CHECK (amount > 0),
    currency            CHAR(3) NOT NULL,
    category_id         UUID REFERENCES money_categories(id),
    title               TEXT NOT NULL DEFAULT '',
    related_entry_id    UUID REFERENCES money_entries(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, record_id),
    CHECK (related_entry_id IS NULL OR related_entry_id <> id)
);

CREATE INDEX idx_money_entries_category ON money_entries (category_id);
CREATE INDEX idx_money_entries_related ON money_entries (related_entry_id)
    WHERE related_entry_id IS NOT NULL;

CREATE TABLE merchants (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    canonical_name      TEXT NOT NULL,
    merchant_type       TEXT,
    place_ref           TEXT,
    canonical_merchant_id UUID REFERENCES merchants(id),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (canonical_merchant_id IS NULL OR canonical_merchant_id <> id)
);

CREATE INDEX idx_merchants_owner_name ON merchants (owner_id, canonical_name);

CREATE TABLE merchant_aliases (
    id                  UUID PRIMARY KEY,
    merchant_id         UUID NOT NULL REFERENCES merchants(id),
    alias               TEXT NOT NULL,
    normalized_alias    TEXT NOT NULL,
    source              TEXT NOT NULL DEFAULT 'user',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, normalized_alias)
);

CREATE TABLE item_identities (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    kind                TEXT NOT NULL CHECK (
        kind IN ('product', 'dish', 'drink', 'service', 'subscription',
                 'ticket', 'digital_good', 'other')
    ),
    canonical_name      TEXT NOT NULL,
    brand               TEXT,
    variant             TEXT,
    merchant_id         UUID REFERENCES merchants(id),
    barcode             TEXT,
    external_ids        JSONB NOT NULL DEFAULT '{}'::jsonb,
    canonical_item_id   UUID REFERENCES item_identities(id),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (canonical_item_id IS NULL OR canonical_item_id <> id)
);

CREATE INDEX idx_items_owner_name ON item_identities (owner_id, canonical_name);
CREATE INDEX idx_items_barcode ON item_identities (owner_id, barcode)
    WHERE barcode IS NOT NULL;

CREATE TABLE item_aliases (
    id                  UUID PRIMARY KEY,
    item_identity_id    UUID NOT NULL REFERENCES item_identities(id),
    alias               TEXT NOT NULL,
    normalized_alias    TEXT NOT NULL,
    source              TEXT NOT NULL DEFAULT 'user',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (item_identity_id, normalized_alias)
);

CREATE TABLE consumption_events (
    id                  UUID PRIMARY KEY,
    record_id           UUID NOT NULL UNIQUE REFERENCES ledger_records(id),
    money_entry_id      UUID UNIQUE,
    scene               TEXT NOT NULL CHECK (
        scene IN ('online_purchase', 'offline_purchase', 'delivery', 'dine_in',
                  'drink', 'service', 'subscription', 'transport',
                  'entertainment', 'travel', 'other')
    ),
    merchant_id         UUID REFERENCES merchants(id),
    merchant_name_raw   TEXT,
    channel_key         TEXT,
    channel_name_raw    TEXT,
    place_ref           TEXT,
    rating              SMALLINT CHECK (rating BETWEEN 1 AND 5),
    would_repeat        BOOLEAN,
    note                TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (money_entry_id, record_id)
        REFERENCES money_entries (id, record_id)
);

CREATE INDEX idx_consumption_events_merchant ON consumption_events (merchant_id);
CREATE INDEX idx_consumption_events_scene ON consumption_events (scene);

CREATE TABLE consumption_lines (
    id                  UUID PRIMARY KEY,
    event_id            UUID NOT NULL REFERENCES consumption_events(id),
    item_identity_id    UUID REFERENCES item_identities(id),
    raw_name            TEXT NOT NULL,
    quantity            NUMERIC(12,4) CHECK (quantity > 0),
    unit                TEXT,
    amount              NUMERIC(18,4),
    content_category    TEXT,
    note                TEXT NOT NULL DEFAULT '',
    sort_order          INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_consumption_lines_event
    ON consumption_lines (event_id, sort_order, id);
CREATE INDEX idx_consumption_lines_item ON consumption_lines (item_identity_id);

CREATE TABLE ledger_record_sources (
    record_id           UUID NOT NULL REFERENCES ledger_records(id),
    source_id           UUID NOT NULL REFERENCES capture_sources(id),
    role                TEXT NOT NULL DEFAULT 'evidence',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (record_id, source_id, role)
);

CREATE TABLE recurring_commitments (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    kind                TEXT NOT NULL CHECK (
        kind IN ('subscription', 'membership', 'regular_service', 'regular_purchase',
                 'fixed_expense', 'regular_income')
    ),
    title               TEXT NOT NULL,
    merchant_id         UUID REFERENCES merchants(id),
    item_identity_id    UUID REFERENCES item_identities(id),
    expected_amount     NUMERIC(18,4) CHECK (expected_amount > 0),
    currency            CHAR(3) NOT NULL,
    recurrence_rule     TEXT NOT NULL,
    timezone            TEXT NOT NULL DEFAULT 'Asia/Shanghai',
    next_due_at         TIMESTAMPTZ NOT NULL,
    auto_renew          BOOLEAN,
    remind_before       INTERVAL NOT NULL DEFAULT INTERVAL '3 days',
    state               TEXT NOT NULL CHECK (state IN ('active', 'paused', 'ended')),
    last_record_id      UUID REFERENCES ledger_records(id),
    revision            INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_recurring_due
    ON recurring_commitments (owner_id, state, next_due_at);

CREATE TABLE spending_intents (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    intent_type         TEXT NOT NULL CHECK (
        intent_type IN ('buy', 'eat', 'drink', 'visit', 'subscribe', 'renew',
                        'cancel', 'replace', 'other')
    ),
    title               TEXT NOT NULL,
    item_identity_id    UUID REFERENCES item_identities(id),
    merchant_id         UUID REFERENCES merchants(id),
    place_ref           TEXT,
    expected_amount     NUMERIC(18,4) CHECK (expected_amount > 0),
    currency            CHAR(3) NOT NULL,
    desired_start       TIMESTAMPTZ,
    desired_end         TIMESTAMPTZ,
    priority            TEXT NOT NULL CHECK (priority IN ('low', 'normal', 'high')),
    state               TEXT NOT NULL CHECK (
        state IN ('inbox', 'considering', 'planned', 'due', 'completed',
                  'skipped', 'cancelled')
    ),
    reason              TEXT,
    completed_record_id UUID REFERENCES ledger_records(id),
    revision            INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (desired_end IS NULL OR desired_start IS NULL OR desired_end >= desired_start)
);

CREATE INDEX idx_intents_owner_state
    ON spending_intents (owner_id, state, desired_start);

CREATE TABLE budget_targets (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    category_id         UUID REFERENCES money_categories(id),
    budget_month        DATE NOT NULL CHECK (
        EXTRACT(DAY FROM budget_month) = 1
    ),
    monthly_amount      NUMERIC(18,4) NOT NULL CHECK (monthly_amount > 0),
    currency            CHAR(3) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    revision            INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_budget_targets_total_active
    ON budget_targets (owner_id, currency, budget_month)
    WHERE category_id IS NULL AND active;
CREATE UNIQUE INDEX uq_budget_targets_category_active
    ON budget_targets (owner_id, currency, budget_month, category_id)
    WHERE category_id IS NOT NULL AND active;

CREATE TABLE external_references (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_id           UUID NOT NULL,
    relation            TEXT NOT NULL,
    target_uri          TEXT NOT NULL CHECK (target_uri LIKE 'shadow://%'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_type, source_id, relation, target_uri)
);

CREATE TABLE asset_bindings (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_id           UUID NOT NULL,
    asset_id            UUID NOT NULL,
    asset_reference_id  UUID,
    usage               TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at         TIMESTAMPTZ,
    UNIQUE (source_type, source_id, asset_id, usage)
);

CREATE TABLE reminders (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    reminder_key        TEXT NOT NULL,
    source_type         TEXT NOT NULL,
    source_id           UUID NOT NULL,
    due_at              TIMESTAMPTZ NOT NULL,
    state               TEXT NOT NULL CHECK (state IN ('pending', 'read', 'handled', 'dismissed')),
    payload             JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, reminder_key)
);

CREATE TABLE outbox_events (
    id                  UUID PRIMARY KEY,
    event_type          TEXT NOT NULL,
    aggregate_type      TEXT NOT NULL,
    aggregate_id        UUID NOT NULL,
    payload             JSONB NOT NULL,
    attempts            INTEGER NOT NULL DEFAULT 0,
    available_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at        TIMESTAMPTZ,
    last_error_code     TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_outbox_pending
    ON outbox_events (available_at, id) WHERE delivered_at IS NULL;

CREATE TABLE background_jobs (
    id                  UUID PRIMARY KEY,
    job_type            TEXT NOT NULL,
    idempotency_key     TEXT NOT NULL UNIQUE,
    payload             JSONB NOT NULL,
    state               TEXT NOT NULL CHECK (state IN ('pending', 'running', 'succeeded', 'failed')),
    attempts            INTEGER NOT NULL DEFAULT 0,
    available_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at           TIMESTAMPTZ,
    locked_by           TEXT,
    last_error_code     TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_background_jobs_ready
    ON background_jobs (available_at, id) WHERE state IN ('pending', 'failed');

CREATE TABLE audit_events (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    actor_type          TEXT NOT NULL,
    actor_id            TEXT NOT NULL,
    action              TEXT NOT NULL,
    aggregate_type      TEXT NOT NULL,
    aggregate_id        UUID NOT NULL,
    details             JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_aggregate
    ON audit_events (aggregate_type, aggregate_id, occurred_at DESC);

-- Authentication and delivery support. Tokens, authorization codes and raw
-- credentials are never persisted in these tables.
CREATE TABLE local_identities (
    id                  UUID PRIMARY KEY,
    issuer              TEXT NOT NULL,
    subject             TEXT NOT NULL,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at       TIMESTAMPTZ,
    UNIQUE (issuer, subject)
);

CREATE TABLE browser_sessions (
    id                  UUID PRIMARY KEY,
    identity_id         UUID NOT NULL REFERENCES local_identities(id),
    session_hash        BYTEA NOT NULL UNIQUE,
    groups_snapshot     JSONB NOT NULL DEFAULT '[]'::jsonb,
    expires_at          TIMESTAMPTZ NOT NULL,
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_browser_sessions_expiry
    ON browser_sessions (expires_at) WHERE revoked_at IS NULL;

CREATE TABLE oidc_transactions (
    id                      UUID PRIMARY KEY,
    state_hash              BYTEA NOT NULL UNIQUE,
    browser_binding_hash    BYTEA NOT NULL,
    nonce_hash              BYTEA NOT NULL,
    pkce_verifier_ciphertext BYTEA NOT NULL,
    redirect_uri            TEXT NOT NULL,
    return_to               TEXT NOT NULL DEFAULT '/',
    expires_at              TIMESTAMPTZ NOT NULL,
    consumed_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idempotency_records (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    operation           TEXT NOT NULL,
    idempotency_key     TEXT NOT NULL,
    request_hash        BYTEA NOT NULL,
    response_status     INTEGER,
    response_body       JSONB,
    resource_id         UUID,
    expires_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, operation, idempotency_key)
);

CREATE INDEX idx_idempotency_records_expiry
    ON idempotency_records (expires_at);

CREATE TABLE user_preferences (
    owner_id            TEXT PRIMARY KEY,
    default_currency    CHAR(3) NOT NULL,
    timezone            TEXT NOT NULL,
    locale              TEXT NOT NULL DEFAULT 'zh-CN',
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE import_batches (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    idempotency_key     TEXT NOT NULL,
    request_hash        BYTEA NOT NULL,
    platform            TEXT NOT NULL,
    state               TEXT NOT NULL CHECK (state IN ('open', 'completed')),
    row_count           INTEGER NOT NULL,
    created_count       INTEGER NOT NULL,
    duplicate_count     INTEGER NOT NULL,
    skipped_count       INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, idempotency_key)
);

CREATE TABLE import_review_items (
    id                          UUID PRIMARY KEY,
    owner_id                    TEXT NOT NULL,
    batch_id                    UUID NOT NULL REFERENCES import_batches(id),
    source_id                   UUID NOT NULL REFERENCES capture_sources(id),
    record_id                   UUID NOT NULL REFERENCES ledger_records(id),
    source_external_id          TEXT NOT NULL,
    raw_merchant_name           TEXT,
    raw_item_names              JSONB NOT NULL DEFAULT '[]'::jsonb,
    normalized_merchant_id      UUID REFERENCES merchants(id),
    duplicate_of_record_id      UUID REFERENCES ledger_records(id),
    refund_candidate_entry_id   UUID REFERENCES money_entries(id),
    amount_anomaly_reason       TEXT,
    review_state                TEXT NOT NULL CHECK (review_state IN ('pending', 'resolved', 'dismissed')),
    resolution                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    revision                    INTEGER NOT NULL CHECK (revision > 0),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE merchant_normalization_rules (
    id                      UUID PRIMARY KEY,
    owner_id                TEXT NOT NULL,
    match_kind              TEXT NOT NULL CHECK (match_kind = 'raw_merchant_exact'),
    normalized_value        TEXT NOT NULL,
    merchant_id             UUID NOT NULL REFERENCES merchants(id),
    explanation             TEXT NOT NULL,
    evidence_count          INTEGER NOT NULL CHECK (evidence_count > 0),
    source_review_item_id   UUID NOT NULL REFERENCES import_review_items(id),
    active                  BOOLEAN NOT NULL DEFAULT TRUE,
    revision                INTEGER NOT NULL CHECK (revision > 0),
    revoked_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_merchant_rules_active
    ON merchant_normalization_rules (owner_id, normalized_value) WHERE active;

CREATE TABLE archive_evidence_links (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    record_id           UUID NOT NULL REFERENCES ledger_records(id),
    asset_binding_id    UUID NOT NULL REFERENCES asset_bindings(id),
    archive_uri         TEXT NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    revision            INTEGER NOT NULL CHECK (revision > 0),
    released_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, record_id, asset_binding_id, archive_uri)
);

CREATE TABLE use_cycles (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    item_identity_id    UUID NOT NULL REFERENCES item_identities(id),
    source_record_id    UUID REFERENCES ledger_records(id),
    label               TEXT,
    started_at          TIMESTAMPTZ NOT NULL,
    expected_end_at     TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,
    state               TEXT NOT NULL CHECK (state IN ('active', 'completed', 'cancelled')),
    note                TEXT NOT NULL DEFAULT '',
    revision            INTEGER NOT NULL CHECK (revision > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (expected_end_at IS NULL OR expected_end_at >= started_at),
    CHECK ((state = 'active' AND ended_at IS NULL) OR
           (state IN ('completed', 'cancelled') AND ended_at >= started_at))
);

CREATE TABLE forecast_runs (
    id                  UUID PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    as_of               DATE NOT NULL,
    timezone            TEXT NOT NULL,
    horizon_days        INTEGER NOT NULL CHECK (horizon_days BETWEEN 1 AND 365),
    algorithm_version   TEXT NOT NULL,
    input_snapshot      JSONB NOT NULL,
    input_hash          BYTEA NOT NULL,
    output_hash         BYTEA NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner_id, algorithm_version, input_hash)
);

CREATE TABLE forecast_items (
    id                  UUID PRIMARY KEY,
    run_id              UUID NOT NULL REFERENCES forecast_runs(id),
    source_key          TEXT NOT NULL,
    kind                TEXT NOT NULL CHECK (kind IN ('commitment_due', 'repeat_purchase', 'use_cycle_end')),
    target_uri          TEXT NOT NULL,
    predicted_at        TIMESTAMPTZ NOT NULL,
    expected_amount     NUMERIC(18,4),
    currency            CHAR(3),
    confidence          NUMERIC(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    explanation         TEXT NOT NULL,
    evidence            JSONB NOT NULL,
    expires_at          TIMESTAMPTZ NOT NULL,
    state               TEXT NOT NULL CHECK (state IN ('active', 'dismissed')),
    revision            INTEGER NOT NULL CHECK (revision > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, source_key),
    CHECK (expected_amount IS NULL OR (expected_amount > 0 AND currency IS NOT NULL))
);

-- Cross-table invariants which migrations must implement with deferred constraint
-- triggers or transaction-level service validation:
-- 1. consumption records have exactly one ConsumptionEvent;
-- 2. money_only records never have a ConsumptionEvent;
-- 3. every referenced object belongs to the same owner;
-- 4. state transitions are draft -> confirmed -> voided only;
-- 5. confirmed/voided timestamps and revision increments are atomic;
-- 6. completing an Intent and linking its Record happen in one transaction.
